### ISSUE TITLE
MultiAreaConditioning Compatibility

### ISSUE THREAD

**Issue by MaxLanc** [hlky/AIT#1]
I have been using AIT for a while now and while it is REALLY FAST there are some kinks I've found out.
I'm using the MultiAreaConditioning node from this repo: https://github.com/Davemane42/ComfyUI_Dave_CustomNode

And when using the LoadAITemplate node connected to the normal KSampler it pukes out the following error.
It does with any combination in the inputs of MultiAreaCond, besides the default of two conditions only
![imagen](https://github.com/hlky/AIT/assets/95586248/a3bd05b6-4343-474d-86bf-d97175b3d7fc)

And this is the related workspace to the node, all other nodes to the right of the pic are the usual hi res fix and face detail combo
![imagen](https://github.com/hlky/AIT/assets/95586248/a433b1e5-bf17-4122-a598-ffba2e0de058)

Is there any chance of adding compatibility or a patch for it?

**Comment by hlky** [comment]
Not an issue. Use modules that supports the batch size you want to run.

**Comment by MaxLanc** [comment]
So the node is using batch? Interesting, thanks for the answer!
