### ISSUE TITLE
Latest ComfyUI updates break plugin on Windows.

### ISSUE THREAD

**Issue by cherrerajobs** [hlky/AIT#2]
I'm not sure what is causing it but the ksampler is throwing a `'tuple' object has no attribute 'model'` error. Maybe caused by changes to the sampler here?:
https://github.com/comfyanonymous/ComfyUI/commit/4eab00e14bc0b52a9c688486d7ee8b392e01020

**Comment by hlky** [comment]
fixed [84ab26f](https://github.com/hlky/AIT/commit/84ab26f5d77cbfecf1b002366d6cca19d78216e0)
